export enum Errors {
    USER_NOT_FOUND = "Пользователь с таким email или паролем не найден!",
    ALREADY_REGISTERED = "Пользователь с таким email уже зарегестрирован!",
    RT_HASH_NOT_FOUND = "Пользователь вышел из аккаунта!",
    RT_HASH_INVALID = "Неверный refresh токен",
    NOT_AUTHENTICATED = "access токен не валидный!",
    NOT_OBJECT_ID = "Не является ObjectId",
    NOT_AUTHORIZED = "Пользователь не авторизован для этого действия!",
    CATEGORY_NOT_EXIST = "Категория с таким id не существует!",
    CANT_CHANGE_SYSTEM_CATEGORY = "Нельзя удалять системные категории!",
    NOT_SYSTEM_CATEGORY = "Не системная категория!",
    MISMATCH_CATEGORIES_ID = "Нельзя удалить чужую кастомную категорию!!",
    CONNECTION_ERROR = "Ошибка подключения к серверу!",
    SERVER_ERROR = "Ошибка на сервере 404!",
    UNEXPECTED_ERROR = "Неизвестная ошибка!",
    USER_ALREADY_IN_KENNEL = "Пользователь уже в одном из питомников",
    YOU_ALREADY_IN_KENNEL = "У вас уже есть заявленный питомник",
    USER_IS_ADMIN = "Пользователь является админом",
    PET_NOT_FOUND = "Питомец с таким Id не найден",
}
